name:                aoc
version:             0.1.0.0
github:              "encse/adventofcode_haskell"
license:             BSD3
author:              "David Nemeth Csoka"
maintainer:          "encse@csokavar.hu"
copyright:           "2019 David Nemeth Csoka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/encse/adventofcode_haskell#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         src
    default-extensions:
    - MultiWayIf
    - LambdaCase
    dependencies:
    - containers
    - parsec
    - matrices
    - vector
    - ansi-terminal
    - deepseq
    - text
    - flow
    - criterion
    - mtl
    - ListZipper
